source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'wechatFuniOS' do
    pod 'Alamofire', '~> 4.5'
    pod 'PureLayout'
    pod 'AlamofireImage', '~> 3.3'
end
